# Generated by Django 4.1.5 on 2023-02-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0003_brand_alter_product_guarantee_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
