# Generated by Django 4.1.5 on 2023-02-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('issue_date', models.DateTimeField(verbose_name='Дата выдачи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'store"."orders',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
                'db_table': 'store"."order_statuses',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар и заказ',
                'verbose_name_plural': 'Товары и заказы',
                'db_table': 'store"."product_orders',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('status', models.BooleanField(default=False, verbose_name='Статус корзины')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина заказов',
                'verbose_name_plural': 'Корзины заказов',
                'db_table': 'store"."buckets',
            },
        ),
    ]
