# Generated by Django 4.1.5 on 2023-02-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0008_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='count',
        ),
    ]
