# Generated by Django 4.1.7 on 2023-02-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0012_city_person_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='hometown',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
