# Generated by Django 4.1.7 on 2023-03-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0014_topping_pizza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
