# Generated by Django 4.1.7 on 2023-03-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0015_delete_pizza_delete_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'test"."persons',
            },
        ),
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('monolith.person',),
        ),
    ]
