# Generated by Django 4.1.7 on 2023-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0016_person_myperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='MyPerson',
        ),
        migrations.AlterField(
            model_name='order',
            name='issue_date',
            field=models.DateTimeField(null=True, verbose_name='Дата выдачи'),
        ),
    ]
